// Generated by CoffeeScript 1.8.0

/**
@author
@description
@name com_contentController

@Possible actions:
 getContentById

@Error codes:
 004 - MISSING_ELEMENT_ERROR : Content with ID:
 003 - MISSING_PARAMETERS_ERROR
 003 - MISSING_PARAMETERS_ERROR : Language Code :
 666 - ACCESS_DENIED!
 */


/* @ngInject */

(function() {
  module.exports = function($scope, $restManager, $constantManager) {


    /**
     * @FUNCTION GET CONTENT USING CONTENT {{ID}}
     * @PARAMS {{NONE}}
     * */
    $scope.getContentById = function(id, language){

      //GENERATE REQUEST USING $RESTMANAGER SERVICE
      $restManager.generateRequest($constantManager.apiUrl).post({

          //SET COMPONENT AND ACTION
          component: "com_content", action: "getContentById",

          //SET DATA PARAMETRS
          data: {
            "contentId": 2,
            "languageCode": "en"
          }
        },

        //GET SUCCESS RESPONCE DATA
        function success(response) {
          console.info(response)
        },

        //GET UNSACCESS RESPONCE DATA
        function (error) {
          console.warn(error);
        });
    };


    //getContentById(id, language)
  };

}).call(this);
